### ISSUE TITLE
Onboarding new validators

### ISSUE THREAD

**Issue by al3mart** [paseo-network/paseo-action-submission#20]
This issue describes a somewhat more structured process to add validators.

Contributors will need to open a PR adding or appending content to the `paseo-validators` folder.
- Labeled as [`new validator`](https://github.com/paseo-network/paseo-rfcs/labels/new%20validator).

Said folder will contain a file per each team providing infrastructure to the network, similarly to:

```
paseo-rfcs
└── paseo-validators
     ├── team-0.yml
     └── team-1.yml
```

Each file will have a structure similar to:

```yaml
identity:
  display: <display name of validator> # display would be the only expected value
  email: <hi@email.com>
  website: <web.io>
  twitter: <@twitter>
  discord: <#discord>
  riot: <@>

accounts:
  0:
    identity: # this identity section is not mandatory
      display: <this concrete validator display name> 
    staking_proxy: <staking_proxy AccountId>
    stash: <stash AccountId>
```

The PR will be then reviewed by the maintainers of Paseo network and once merged the validator will be funded with the minimum required amount to be part of the active set as well as its identity set on chain.

Following the infrastructure provider can proceed with bonding and setting the session keys. These steps are described at the corresponding section of the Polkadot wiki:
- [Run a Validator](https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot)
